### ISSUE TITLE
Salt and hash passwords for Users and FieldWorkers

### ISSUE THREAD

**Issue by benjamin-heasly** [benjamin-heasly/openhds-rest#105]
Currently User and FieldWorker passwords are stored as plain text.

Incorporate bcrypt (or better?) to salt and hash passwords.

Make the "password" fields transient and ignored by the database.

Only persist the salted, hashed "passwordHash" fields.

**Comment by benjamin-heasly** [comment]
BCrypt was easy to implement when we did it on the openhds-tablet.

And see Spring support: http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/crypto/bcrypt/BCrypt.html

Let's box this at about 1 day.

**Comment by benjamin-heasly** [comment]
0f51ca404482d62af7f545903ff5fbdfe673e97a contains these changes.

Plaintext passwords may come over the wire and in memory, but are never persisted.

User and FieldWorker each has a passwordHash field, and no plain text password field.

UserRegistration and FieldWorkerRegistration each has a plain text password field.

UserService and FieldWorkerService immediately hash the registration password with bcrypt before persisting.

**Comment by wolfe-lienhardt** [comment]
Awesome that you were able to tap into Spring to do it. GJ
