### ISSUE TITLE
Disable basic auth on localhost

### ISSUE THREAD

**Issue by munk** [benjamin-heasly/openhds-rest#139]
End to end tests for the angular front end are failing because of an http authentication alert box after the first request. Unfortunately, Selenium isn't able to deal with this sort of alert, so it makes automated end to end testing impossible.

An alternative to allow local testing would be to disable http authentication for requests from localhost.

**Comment by benjamin-heasly** [comment]
Can the tests avoid the alert dialog by providing credentials preemptively?  Maybe even by including them in the URL, like `http://username:password@example.com`?

If something like that won't work, I have no objection to disabling auth. for localhost.

**Comment by munk** [comment]
Adding the credentials to the url works when I try it manually. I'll try adding the credentials in a test and see how it works out. If it's successful I'll close this ticket.

**Comment by munk** [comment]
Adding the credentials to the url still results in the alert dialog, so disabling auth for localhost is probably the simplest solution.
