### ISSUE TITLE
Add OpenHDS events module

### ISSUE THREAD

**Issue by benjamin-heasly** [benjamin-heasly/openhds-rest#34]
Add the events module, which keeps track of system events and facilitates integration with external system.

**Comment by benjamin-heasly** [comment]
UuidRestController should have a utility for logging Registrations.  And the templated POST and PUT endpoints should log successful Registrations.

**Comment by bruceMacLeod** [comment]
This would be an incredibly useful feature if you can manage it.

**Comment by benjamin-heasly** [comment]
In the code I'm working from ([here](https://github.com/USM-RCG/openhds-server/tree/old-master/events)) I didn't find any integration tests.  So I'm making up some of the behavior in a way that seems reasonable to me.

The behavior might need to be updated by someone who understands the events requirements better.  I am not going to block on this.

Here is the behavior I'm going to implement and test before moving on:

Services can create Events, which represent anything interesting.  Events have a string data payload and some queryable fields like entity type, action type, date-time, and user.

Events are also associated with EventMetadata, which keep track of external systems that are interested in the Events.  The EventMetadata identify an external system, the status of an event as viewed by that system, and the number of times the system has read a given Event.

External systems should not care about each other, so changes to the Metadata associated with one system should not effect the Metadata associated with another system.

If a new external system queries for events, it sees all events.  As a side effect of the query, new default EventMetadata are created for that system and associated with all events.

If the same system queries for events again, the query will make use of the existing metadata.  This will allow interesting queries like "get all the events that this system hasn't read yet".

**Comment by benjamin-heasly** [comment]
2bc95ac1c3853ecbb23daa5422e137ab2ee38cdf contains events model, service, and resource, and tests as described above.
