### ISSUE TITLE
Create JpaRepository type hierarchy that mirrors Services

### ISSUE THREAD

**Issue by wolfe-lienhardt** [benjamin-heasly/openhds-rest#38]
I think it would make sense to have a repository hierarchy that mirrored the new service hierarchy where things like "findByExtId()" could be written once in the "AuditableCollectedRepository" and used by all entity specific repositories where finding by extId would be helpful.

**Comment by benjamin-heasly** [comment]
I like that idea.

**Comment by wolfe-lienhardt** [comment]
This may not be as straight forward as initially anticipated:

http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-behaviour-for-all-repositories

**Comment by wolfe-lienhardt** [comment]
Oh nevermind!

The @NoRepositoryBean annotation seems to have solved the problem I was running into!

Phew!

**Comment by wolfe-lienhardt** [comment]
Resolved in commit b2c7c69d40f825943476d1fe707da4061b9921d9
