### ISSUE TITLE
Refactor Domain Hierarchy?

### ISSUE THREAD

**Issue by wolfe-lienhardt** [benjamin-heasly/openhds-rest#40]
Do we want to change the hierarchy of the OpenHDS Domain classes to 

UuidIdentifiable -> Auditable -> AuditableCreated (No extId) -> AuditableCollected (Has extId)

This would mean that anything collected would have extIds and that the "ExtIdentifiable" type may be redundant.

This hierarchy also means that UuidIdentifiable could be a class and not an interface.

The design would be cleaner/more straight forward - but I like I am overlooking something major in terms of motivation for the current way it's designed with UuidIdentifiable and ExtIdentifiable being separate interfaces. 

I assumed the current design is the way it is because of the fact that there are 'type irregularities' like FieldWorker who has an extId but isn't collectable. I think it is desirable to have cases like this 'squashed' into the proposed hierarchy (i.e. making FieldWorker have a FieldWorkerId instead of an extId, etc).

We spoke about this in person - but I'd like to come to a solid conclusion on steps forward.

**Comment by benjamin-heasly** [comment]
I want to make that change and smooth out the irregularities.

I think it would be expressive and self-documenting to keep
UuidIdentifiable and ExtIdentifiable as explicit interfaces.

What if we keep them and let each one be implemented by Auditable or
AuditableCollected?

In that case, ExtIdentifiable could be it's own thing and not have to
extend UuidIdentifiable.

Does that make sense / seem good?

**Comment by wolfe-lienhardt** [comment]
Would we still want to make the distinction between things that are "Created" vs "Collected"?

I.e. a Membership, which doesn't have its own extId but is "Created" when an Individual which does have its own extId is "Collected" by a Field Worker.

Would it be enough to make types like Membership, Relationship, and Residency all subtypes of AuditableEntity - whereas things like Individual, Location, and SocialGroup would be subtypes of AuditableCollectedEntity, which has more information like FieldWorker etc, but also implements ExtIdentifiable?

In this way the type hierarchy would look something like this:

**AuditableEntity (Implements UuidIdentifiable)**
(Subtypes: Membership, Relationship, Residency, etc)
**AuditableCollectedEntity(Extends AuditableEntity)(Implements ExtIdentifiable)**
(Subtypes: Individual, Location, LocationHierarchy, SocialGroup, etc)

Things like Membership would not have a field worker associated with it since a fieldworker never really "collected" a membership.

All things would have UUIDs.

Only things Collected by a field worker would have ExtIds.

Is that what you were thinking?

**Comment by benjamin-heasly** [comment]
I think that's a good hierarchy the way you put it.  I like that it
simplifies things and removes a layer.

But maybe removing field worker from Membership etc. would be too big a
change? Maybe people want that for statistics or reporting?  I don't have a
good sense for that.

So I think we should either leave in the extra layer so that Membership
etc. still has a field worker, or else stop and be blocked until we can ask
about that requirement.

**Comment by wolfe-lienhardt** [comment]
I will make the new layer and move forward - going back and changing it would not be that much work if need be.

**Comment by wolfe-lienhardt** [comment]
Resolved in commit b2c7c69d40f825943476d1fe707da4061b9921d9
