### ISSUE TITLE
Implement Spring Validator(s)

### ISSUE THREAD

**Issue by wolfe-lienhardt** [benjamin-heasly/openhds-rest#44]
Validation in the services will be handled by implementing the Spring Validator service as described here:
http://docs.spring.io/spring/docs/current/spring-framework-reference/html/validation.html

This will provide an obvious and convenient location for all validation to take place as well as a central area to catch exceptions and log them before throwing them.

**Comment by wolfe-lienhardt** [comment]
Validation will no longer be handled by Spring validators, but instead through a combination of a validation method in the services and JSR-303 annotations.

**Comment by bruceMacLeod** [comment]
It would be helpful to understand the reason for the change.

**Comment by wolfe-lienhardt** [comment]
The really wasn't any benefit to using the Spring validator the way that was planned and infact would have made things more troublesome because we would have been forced to use the Java Errors type. 

Using our own validators gives us the exact same functionality with minimal work and allows us to use the ErrorLog and Error work from Russell.
