### ISSUE TITLE
Create Super Tests for Services

### ISSUE THREAD

**Issue by wolfe-lienhardt** [benjamin-heasly/openhds-rest#45]
Create a set of integration tests that test the fields shared among OpenHDS entities which can be extended for each specific entity.

This will allow us to write only 1 set of tests for the fundamental functionality of all the entities like get, get all, etc.

Entity specific implementations will come later as the domain documentation and specification is created with the services.

**Comment by wolfe-lienhardt** [comment]
Closed with https://github.com/benjamin-heasly/openhds-rest/pull/50

**Comment by munk** [comment]
I rely on tests a lot to understand how a system works. I appreciate reducing the amount of test code written here but it obfuscates the intent and reduces its value as documentation. Some additional block comments that at least describe the test cases that are generated would be very helpful.
